config_load_and_split:
  method_loading: "AzureAIDocumentIntelligenceLoader"
  method_splitting: "MarkdownHeaderTextSplitter"
  path: 'D:\work\dataset\comptes-budgetaires'
  export_path: 'D:\work\dataset\comptes-budgetaires\index'
  glob: "**/*.pdf"
  use_multithreading: true
  headers_to_split_on:
    - !!python/tuple ["#", "Header 1"]
    - !!python/tuple ["##", "Header 2"]
    - !!python/tuple ["###", "Header 3"]

config_index:
  docs: 'D:\work\dataset\comptes-budgetaires\index'
  embedding_map: "AzureOpenAIEmbeddings"
  vector_store_map: "AzureSearch"
  index_name: "tables"

config_chat:
  max_tokens: 8000

config_azure_retriever:
  top_k: 3
  index_name: "tables"

config_QA_chain:
  return_source_documents: true

config_conversation:
  temperature: 0
  max_tokens: 1000
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  stop: [' END']
