env_path: "D:/work/amaris/angular_rag-main/rag/.env"

port: 3000

port_front: 4200

chain:
  class_name: "$import:langchain.chains.ConversationalRetrievalChain"
  method:
    name: "from_llm"
    args:
      llm:
        class_name: "$import:langchain_openai.AzureChatOpenAI"
        init_args:
          openai_api_key: "$env:azure_openai_key"
          azure_endpoint: "$env:azure_openai_endpoint"
          openai_api_version: "2023-05-15"
          deployment_name: "$env:azure_openai_deployment_id"

      retriever:
        class_name: "$import:langchain_community.retrievers.AzureCognitiveSearchRetriever"
        init_args:
          service_name: "$env:azure_ai_search_name"
          index_name: "science_papers"
          api_key: "$env:azure_ai_search_key"

          top_k: 3
      
      return_source_documents: true